name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/west.yml
      - config/*.keymap
      - config/*.conf
      - config/boards/**
      - config/core/*
      - config/layers/*
      - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
